version: "3.3"

services:
  my-app:
    build: ./my-app
    image: my-app
    container_name: my-app
    restart: always
    ports:
      - 3000:80
    networks:
      - app-network
  app1:
    build: ./app1
    image: app1
    container_name: app1
    restart: always
    ports:
      - 3001:80
    networks:
      - app-network
  app2:
    build: ./app2
    image: app2
    container_name: app2
    restart: always
    ports:
      - 3002:80
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: always
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - my-app
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
